name: Cache GTest install

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  projectName: CMakeStarterProjectWithTests
  # GTest_VERSION: 1.13.0

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install GTest but do NOT cache it (caching of GTest doesn't work on Ubuntu)
      run: |
        echo sudo apt-get install libgtest-dev
        sudo apt-get install libgtest-dev
        echo sudo apt-get install libgmock-dev
        sudo apt-get install libgmock-dev

        echo Find in /usr
        find /usr/ -iname gtest*.h
        find /usr/ -iname libgtest*.a
        find /usr/ -iname libgtest*.so
        find /usr/ -iname gmock*.h
        find /usr/ -iname libgmock*.a
        find /usr/ -iname libgmock*.so
        find /usr/ -iname gtest*config.cmake
        find /usr/ -iname gmock*config.cmake
        
    - name: CMake configure --- Ninja, Gnu, Debug
      run: |
        echo cmake --preset Ninja-Gnu-Debug
        cmake --preset Ninja-Gnu-Debug
      # echo cmake --preset Ninja-Gnu-Debug -D GTest_DIR=/usr/src/googletest
      # cmake --preset Ninja-Gnu-Debug -D GTest_DIR=/usr/src/googletest

    - name: CMake build --- Ninja, Gnu, Debug
      run: |
        echo cmake --build --preset Ninja-Gnu-Debug
        cmake --build  --preset Ninja-Gnu-Debug

    - name: CMake run --- Ninja, Gnu, Debug
      run: |
        echo cmake --build --preset Ninja-Gnu-Debug
        cmake --build --preset Ninja-Gnu-Debug --target run

    - name: CMake unit test --- Ninja, Gnu, Debug
      run: |
        echo cmake --build --preset Ninja-Gnu-Debug
        cmake --build --preset Ninja-Gnu-Debug --target runUnitTest


  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Cache GTest
      id: mac-GTest-ID-installed-cache1
      uses: actions/cache@v3
      with:
        path: /usr/local/Cellar
        key: mac-GTest-KEY-installed-cache1

    - name: Is GTest cached? Do not install GTest!
      if: steps.mac-GTest-ID-installed-cache1.outputs.cache-hit == 'true'
      run: |
        echo YES cached!
        find /usr/local/Cellar/ -iname gtest*.h
        find /usr/local/Cellar/ -iname gmock*.h

    - name: Is GTest not yet cached? Install GTest and cache it!
      if: steps.mac-GTest-ID-installed-cache1.outputs.cache-hit != 'true'
      run: |
        echo brew install googletest
        brew install googletest

        echo NO not yet cached!
        find /usr/local -iname gtest.h
        find /usr/local -iname libgtest*.a
        find /usr/local -iname libgtest*.so
        find /usr/local -iname libgtest*.dylib
        find /usr/local -iname gmock*.h
        find /usr/local -iname libgmock*.a
        find /usr/local -iname libgmock*.dylib
        find /usr/local -iname libgmock*.so
        find /usr/local -iname gtest?config.cmake
        find /usr/local -iname gmock?config.cmake

    - name: CMake configure --- Ninja, Clang, Debug
      run: |
        echo cmake --preset Ninja-Clang-Debug -D GTest_DIR=/usr/local/Cellar/googletest
        cmake --preset Ninja-Clang-Debug -D GTest_DIR=/usr/local/Cellar/googletest

    - name: CMake build --- Ninja, Clang, Debug
      run: |
        echo cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug

    - name: CMake run --- Ninja, Clang, Debug
      run: |
        echo cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug --target run

    - name: CMake unit test --- Ninja, Clang, Debug
      run: |
        echo cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug --target runUnitTest


  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake configure --- Ninja, Msvc, Debug
      run: |
        echo cmake --preset Ninja-Msvc-Debug
        cmake --preset Ninja-Msvc-Debug

    - name: CMake build --- Ninja, Msvc, Debug
      run: |
        echo cmake --build --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug

    - name: CMake run --- Ninja, Msvc, Debug
      run: |
        echo cmake --build --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug --target run

    - name: CMake unit test --- Ninja, Msvc, Debug
      run: |
        echo cmake --build --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug --target runUnitTest
