name: Cache GTest install

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  projectName: CMakeStarterProjectWithTests
  GTest_VERSION: 1.13.0

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install GTest but do NOT cache it (caching of GTest doesn't work on Ubuntu)
      run: |
        echo sudo apt-get install libgtest-dev
        sudo apt-get install libgtest-dev

        echo Find in /usr
        find /usr/ -iname gtest.h
        
    - name: CMake configure --- Ninja, Gnu, Debug
      run: |
        echo cmake --preset Ninja-Gnu-Debug
        cmake --preset Ninja-Gnu-Debug

    - name: CMake build --- Ninja, Gnu, Debug
      run: |
        echo cmake --build --preset Ninja-Gnu-Debug
        cmake --build  --preset Ninja-Gnu-Debug


  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Cache GTest
      id: mac-GTest-ID-installed-cache1
      uses: actions/cache@v3
      with:
        path: /usr/local/Cellar
        key: mac-GTest-KEY-installed-cache1

    - name: Is GTest cached? Do not install GTest!
      if: steps.mac-GTest-ID-installed-cache1.outputs.cache-hit == 'true'
      run: |
        echo YES cached!
        find /usr/local/Cellar/ -iname gtest.h

    - name: Is GTest not yet cached? Install GTest and cache it!
      if: steps.mac-GTest-ID-installed-cache1.outputs.cache-hit != 'true'
      run: |
        echo brew install googletest
        brew install googletest

        echo NO not yet cached!
        find /usr/local/Cellar -iname gtest.h

    - name: CMake configure --- Ninja, Clang, Debug
      run: |
        echo cmake --preset Ninja-Clang-Debug
        cmake --preset Ninja-Clang-Debug

    - name: CMake build --- Ninja, Clang, Debug
      run: |
        echo cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug


  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake configure --- Ninja, Msvc, Debug
      run: |
        echo cmake --preset Ninja-Msvc-Debug
        cmake --preset Ninja-Msvc-Debug

    - name: CMake build --- Ninja, Msvc, Debug
      run: |
        echo cmake --build --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug

