name: Build and run on Linux and Mac with CMakePresets.json

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  singleConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        preset:
        # single config generators
          - Ninja-Gnu-Debug
          - Ninja-Gnu-Release
          - Ninja-Clang-Debug
          - Ninja-Clang-Release
          - Make-Gnu-Debug
          - Make-Gnu-Release
          - Make-Clang-Debug
          - Make-Clang-Release

        linkGTestAsSharedLibrary: 
          # - ON # do not test this option because it works only on with a preinstalled gtest
          - OFF

        exclude:
          - os: macos-latest
            preset: Ninja-Gnu-Debug
          - os: macos-latest
            preset: Ninja-Gnu-Release
          - os: macos-latest
            preset: Make-Gnu-Debug
          - os: macos-latest
            preset: Make-Gnu-Release
        
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo preset = ${{matrix.preset}}
        echo linkGTestAsSharedLibrary = ${{matrix.linkGTestAsSharedLibrary}}

    - name: CMake configure
      run: > 
        cmake --preset ${{matrix.preset}}
        -D linkGTestAsSharedLibrary=${{matrix.linkGTestAsSharedLibrary}}
      
    - name: CMake build
      run: cmake --build --preset ${{matrix.preset}}

    - name: CMake run program
      run: cmake --build --preset ${{matrix.preset}} --target run

    - name: CMake run unit tests (gtest and gmock)
      run: cmake --build --preset ${{matrix.preset}} --target runUnitTest

    - name: CTest run unit tests (gtest and gmock)
      run: ctest --preset ${{matrix.preset}} --output-on-failure


  multiConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        preset:
        # multi config generators
          - NinjaMC-Gnu
          - NinjaMC-Clang
          - Xcode-Clang
        buildType: [Debug, Release]

        linkGTestAsSharedLibrary: 
          # - ON # do not test this option because it works only on with a preinstalled gtest
          - OFF

        exclude:
          - os: ubuntu-latest
            preset: Xcode-Clang
            
          - os: macos-latest
            preset: NinjaMC-Gnu
        
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo preset = ${{matrix.preset}}
        echo buildType = ${{matrix.buildType}}
        echo linkGTestAsSharedLibrary = ${{matrix.linkGTestAsSharedLibrary}}

    - name: CMake configure[]
      run: > 
        cmake --preset ${{matrix.preset}}
        -D linkGTestAsSharedLibrary=${{matrix.linkGTestAsSharedLibrary}}
      
    - name: CMake build
      run: cmake --build --preset ${{matrix.preset}} --config ${{matrix.buildType}}

    - name: CMake run program
      run: cmake --build --preset ${{matrix.preset}} --config ${{matrix.buildType}} --target run

    - name: CMake run unit tests (gtest and gmock)
      run: cmake --build --preset ${{matrix.preset}} --config ${{matrix.buildType}} --target runUnitTest

    - name: CTest run unit tests (gtest and gmock)
      run: ctest --preset ${{matrix.preset}} --config ${{matrix.buildType}} --output-on-failure
