name: Build and run on Windows without CMakePresets.json

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  singleConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compilerCpp: 
          - name: cl
            buildSubDir: Msvc
        buildType: [Debug, Release]
        generator: 
          - name: Ninja
            buildDir: buildNinja
          - name: "NMake Makefiles"
            buildDir: buildMake

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo cl
        cl
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo generator = ${{matrix.generator.name}}
        echo buildType = ${{matrix.buildType}}
        echo compiler = ${{matrix.compilerCpp.name}}

    - name: CMake configure
      run: > 
        cmake -S . 
        -B ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -G "${{matrix.generator.name}}" 
        -D CMAKE_buildType=${{matrix.buildType}} 
        -D CMAKE_CXX_COMPILER=${{matrix.compilerCpp.name}}
      
    - name: CMake build
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8

    - name: CMake run program
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --target run

    - name: CMake run unit tests (gtest and gmock)
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --target runUnitTest

    - name: CTest run unit tests (gtest and gmock)
      run: > 
        ctest 
        --test-dir ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8
        --output-on-failure


  multiConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compilerCpp: 
          - name: cl
            buildSubDir: Msvc
        buildType: [Debug, Release]
        generator: 
          - name: "Ninja Multi-Config"
            buildDir: buildNinjaMC

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1
        
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo cl
        cl
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo generator = ${{matrix.generator.name}}
        echo buildType = ${{matrix.buildType}}
        echo compiler = ${{matrix.compilerCpp.name}}

    - name: CMake configure
      run: > 
        cmake -S . 
        -B ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -G "${{matrix.generator.name}}" 
        -D CMAKE_CXX_COMPILER=${{matrix.compilerCpp.name}}
      
    - name: CMake build
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}

    - name: CMake run program
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}
        --target run

    - name: CMake run unit tests (gtest and gmock)
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}
        --target runUnitTest

    - name: CTest run unit tests (gtest and gmock)
      run: > 
        ctest 
        --test-dir ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8
        --config ${{matrix.buildType}}
        --output-on-failure


  multiArchitecture:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compilerCpp: 
          - name: cl
            buildSubDir: Msvc
        buildType: [Debug, Release]
        generator: 
          - name: Visual Studio 17 2022
            buildDir: buildVS
        architecture:
          - name: win32
            buildSubDir: x32
          - name: x64
            buildSubDir: x64

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Tool versions
      shell: bash
      run: | 
        echo cl
        cl
        echo 
        echo cmake --version
        cmake --version

    - name: Parameter values
      shell: bash
      run: | 
        echo platform = ${{runner.os}}
        echo architecture = ${{matrix.architecture.name}}
        echo generator = ${{matrix.generator.name}}
        echo buildType = ${{matrix.buildType}}
        echo compiler = ${{matrix.compilerCpp.name}}

    - name: CMake configure
      run: > 
        cmake -S . 
        -B ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -G "${{matrix.generator.name}}" 
        -A ${{matrix.architecture.name}}
      
    - name: CMake build
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}

    - name: CMake run program
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}
        --target run

    - name: CMake run unit tests (gtest and gmock)
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}
        --target runUnitTest

    - name: CTest run unit tests (gtest and gmock)
      run: > 
        ctest 
        --test-dir ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}}  
        -j8
        --config ${{matrix.buildType}}
        --output-on-failure
